version: '3.9'

services:
  app:
    image: swr.ru-moscow-1.hc.sbercloud.ru/geekbrains-lecturer/banzai-frontend:latest
    environment:
      API_URL: http://api-gateway:8088
    ports:
      - 4000:80

  inventory:
    build:
      context: ./backend/inventory-service
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - rmq
      - redis
  
  db:
    container_name: model-behavior-db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./cache:/data
    environment:
      REDIS_PORT: 6379

  rmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
