extraEnv:
  - name: MODEL_URL
    value: https://storage.yandexcloud.net/geekbrains-models/models.tar.gz

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  size: 20Gi
  annotations: {}
  volume:
    name: data
    mountPath: /models