name: ML service CI workflow
on:
  workflow_dispatch:
  push:
    paths:
      - 'ml/**'
      - '.github/workflows/ml-service.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'ml/**'
permissions:
  contents: write

jobs:
  deploy-container:
    if: github.ref == 'refs/heads/main'
    #    needs:
    #      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: echo $DOCKER_LOGIN_KEY | docker login --username ru-moscow-1@$DOCKER_LOGIN_USER --password-stdin $DOCKER_IMAGE_REPO_ADDR
        env:
          DOCKER_LOGIN_USER: ${{secrets.SBC_ACCESS_KEY}}
          DOCKER_LOGIN_KEY: ${{secrets.DOCKER_LOGIN_KEY}}
          DOCKER_IMAGE_REPO_ADDR: swr.ru-moscow-1.hc.sbercloud.ru
          DOCKER_REGISTRY: geekbrains-lecturer
      - run: |
          echo "Packaging docker image ..."
          image="$DOCKER_IMAGE_REPO_ADDR/$DOCKER_REGISTRY/banzai-ml"
          tag="$image:${{github.sha}}"
          latest_tag="$image:latest"
          docker build . -t $tag
          docker push $tag
        env:
          DOCKER_IMAGE_REPO_ADDR: swr.ru-moscow-1.hc.sbercloud.ru
          DOCKER_REGISTRY: geekbrains-lecturer